# Generated by Django 4.2.2 on 2024-08-14 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0019_contact_us_timestamp_alter_contact_us_email_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact_Us',
        ),
    ]
